### ISSUE TITLE
X11 is not a requirement

### ISSUE THREAD

**Issue by falkTX** [flathub/studio.kx.carla#3]
The build rules specify `--with-x11` but this is not needed, should be removed.

**Comment by Bleuzen** [comment]
What exactly do you mean?
There is no "--with-x11" in the build file.

However there are two other x11 references.

1) https://github.com/flathub/studio.kx.carla/blob/0556bdd241e7b18c9dfd08b157d9edba34dcfa78/studio.kx.carla.json#L11

This is not defined as a dependency, but a permission. Without it, Carla would not be able to show the frontend on x11. See:
https://docs.flatpak.org/en/latest/sandbox-permissions.html#standard-permissions

2) https://github.com/flathub/studio.kx.carla/blob/0556bdd241e7b18c9dfd08b157d9edba34dcfa78/studio.kx.carla.json#L58

This one may go away after getting pyqt updated anyway, see: https://github.com/flathub/studio.kx.carla/pull/9

---

So I don't see anything to do here, closing.
Feel free to reopen or ask if anything is left.

**Comment by falkTX** [comment]
> What exactly do you mean?
> There is no "--with-x11" in the build file.

There was before regarding pyqt but as you said going away with the PR
