### ISSUE TITLE
Remove jack2 as dependency

### ISSUE THREAD

**Issue by falkTX** [flathub/studio.kx.carla#6]
Carla includes its own jack headers in the source and will open libjack.so.0 on startup to dynamically use JACK as needed.
So `shared-modules/linux-audio/jack2.json` can be removed from the build config, it is never used/needed.

**Comment by Bleuzen** [comment]
done in https://github.com/flathub/studio.kx.carla/commit/6edab7da73052fb58fcab96a6cc243e423f97854
